# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# https://stackoverflow.com/a/72408109/3443137
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# For a lower total time
# the jobs which take longes must come before the faster ones
# because github will start them likely earlier
jobs:         
  example-tauri:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y chromium-browser
      - name: prepare RxDB core
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: tauri install
        working-directory: ./examples/tauri
        run: |
          npm run preinstall
          npm install --legacy-peer-deps -D

      - name: tauri test
        uses: coactions/setup-xvfb@v1
        with:
          working-directory: ./examples/tauri
          run: npm run test